server:
  port: 8443
  max-http-header-size: 8192
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true
  servlet:
    context-path: /
    session:
      timeout: 30m
  compression:
      enabled: true
      mime-types: text/html,text/css,application/javascript,application/json

spring:
  profiles:
    active: prod
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/soaic?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      uri: mongodb://localhost:27017/soaic?maxPoolSize=256
  application:
    name: hellospringboot
  http:
    encoding:
      charset: UTF-8
      force: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    favicon:
      enabled: true
  cache:
    type: redis
    cache-names: soaic
  session:
    store-type: redis
  redis:
    database: 0
    host: 192.168.0.184
    port: 6379
    password:
    jedis:
      pool:
        #连接池支持的最大连接数
        max-active: 1000
        #连接池中连接用完时,新的请求等待时间,毫秒
        max-wait: -1ms
        #连接池中最多可空闲maxIdle个连接
        max-idle: 400
        min-idle: 0
    timeout: 1000ms


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.soaic.hellospringboot.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: false

